### ISSUE TITLE
nettray wireless scan doesn't seem to do anything

### ISSUE THREAD

**Issue by mike-pt** [pcbsd/pcbsd#24]
I noticed for the GUI it seemed to be doing nothing, and indeed even running from console:

sudo pc-nettray wlan0

I click scan and see nothing

**Comment by kmoore134** [comment]
Does "ifconfig wlan0 list scan -v" show anything from CLI?

**Comment by mike-pt** [comment]
this was a old one...  I gave up on pcbsd-utils to be honest.  I use freebsdthe nettray seemed handy for wireless but it always caused me more harm then good,  scan was noy always reliable and the network restart sometimes got stuck so I revert back to use console only. 

Botb freebsd desktop machines I have bow are on CURRENT,  using Lumina-DE. 

If you want I can reinstal the package just to check if its working.

**Comment by kmoore134** [comment]
I've been able to duplicate this here, seeing the issue from "ifconfig" as well on 10.1-RELEASE, sometimes the ifconfig wlan0 list scan returns nothing, which is what the GUI is displaying. This may be fixed in 10.2 though.
