### ISSUE TITLE
Incorrect mount point reported for the root filesystem in Disk Manager

### ISSUE THREAD

**Issue by cubranic** [pcbsd/pcbsd#73]
Running PCBSD-10.1 in Virtual Box using the [official .ova image](http://download.pcbsd.org/iso/10.1-RELEASE/amd64/PCBSD10.1.1-RELEASE-x64-consumer-desktop.ova), I see a discrepancy between the mount point for filesystem tank/ROOT/default reported in the GUI (Disk Manager opened from the Control Panel) vs the command line (both ‘mount’ and ‘df’). The GUI says it’s at “/mnt”, but ‘mount’ says “/“. See attached screenshot for illustration.

![pcbsd - zfs filesystems](https://cloud.githubusercontent.com/assets/600891/6332746/a47e435c-bb3c-11e4-919d-00f76583f12c.png)

**Comment by kmoore134** [comment]
On 02/23/2015 12:17, Davor Cubranic wrote:
>
> Running PCBSD-10.1 in Virtual Box using the official .ova image
> <http://download.pcbsd.org/iso/10.1-RELEASE/amd64/PCBSD10.1.1-RELEASE-x64-consumer-desktop.ova>,
> I see a discrepancy between the mount point for filesystem
> tank/ROOT/default reported in the GUI (Disk Manager opened from the
> Control Panel) vs the command line (both ‘mount’ and ‘df’). The GUI
> says it’s at “/mnt”, but ‘mount’ says “/“. See attached screenshot for
> illustration.
>
> pcbsd - zfs filesystems
> <https://cloud.githubusercontent.com/assets/600891/6332746/a47e435c-bb3c-11e4-919d-00f76583f12c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pcbsd/pcbsd/issues/73>.
>

Its just a left-over ZFS property from the install. When you create a
new BE or update, it'll be automatically fixed.

I've fixed it here now for the next images:

https://github.com/pcbsd/pcbsd/commit/0456df4b1dc7beb8277b9ec1d0197b2949ff6d50

-- 
Kris Moore
PC-BSD Software
iXsystems
