### ISSUE TITLE
pkg query format string with spaces fails

### ISSUE THREAD

**Issue by mrT55** [pcbsd/pcbsd#74]
pkg version: 1.4.12
uname -a
FreeBSD MT2007 10.1-RELEASE-p17 FreeBSD 10.1-RELEASE-p17 #0
KDE: 4.14.2_5

Every sample of a published 'pkg query' where the format string contains one or more space(s)
will fail with: Invalid query: query should contain a format string.
This symptom is repeatable every time.

Example:
  pkg query "Package name = %n, Version = %v, Size = %sh" mysql-server
  Invalid query: query should contain a format string

In this example, the output stops after the first space in the format string, w/o an error message.
  pkg query '%o: %Fp' firefox
    www/firefox:

I performed additional tests and discovered I had two 
different pkg executables as follows:
   /usr/local/sbin/pkg                            (64-bit binary )
   /usr/local/share/pcbsd/bin/pkg                 (sh shell script. I enabled debug mode -xv)
   
My default environment path is:
  echo $PATH
    /usr/local/share/pcbsd/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/pbi/bin:/usr/local/sbin:/usr/local/bin:/usr/home/mark/bin

using the following as a test patern:
   pkg query -e '%#r = 0' '%o'
   
Test with default path from Konsole cmd line:
pkg query -e '%#r = 0' '%o'
    + /usr/sbin/pkg query -e '%#r' = 0 %o
    Invalid query: query should contain a format string
    (This seems to be the source of my original bug report.)

Test directly with the binary:
   /usr/local/sbin/pkg query -e '%#r = 0' '%o'
   -->this works! Gives the expected results.
      NOTE: This effectively bypasses the '/usr/local/share/pcbsd/bin/pkg' script.
      
pkg which /usr/local/sbin/pkg
   /usr/local/sbin/pkg was installed by package pkg-1.4.12

pkg info -f package pkg-1.4.12
pkg: No package(s) matching package
pkg-1.4.12
Name           : pkg
Version        : 1.4.12
Installed on   : Mon Mar  2 12:04:10 EST 2015
Origin         : ports-mgmt/pkg
Architecture   : freebsd:10:x86:64
Prefix         : /usr/local
Categories     : ports-mgmt
Licenses       : BSD2CLAUSE
Maintainer     : portmgr@FreeBSD.org
WWW            : http://wiki.freebsd.org/pkgng
Comment        : Package manager
Shared Libs provided:
        libpkg.so.3
Annotations    :
Flat size      : 9.59MiB
Description    :
Package management tool

WWW: http://wiki.freebsd.org/pkgng

-----
pkg which /usr/local/share/pcbsd/bin/pkg
    /usr/local/share/pcbsd/bin/pkg was installed by package pcbsd-utils-1425579131

pkg info -f pcbsd-utils-1425579131
pcbsd-utils-1425579131
Name           : pcbsd-utils
Version        : 1425579131
Installed on   : Mon Mar  9 20:33:48 EDT 2015
Origin         : sysutils/pcbsd-utils
Architecture   : freebsd:10:x86:64
Prefix         : /usr/local
Categories     : sysutils
Licenses       : BSD
Maintainer     : kmoore@FreeBSD.org
WWW            : https://github.com/pcbsd/pcbsd
Comment        : PC-BSD Command-Line Utilities
Shared Libs required:
        libQt5Network.so.5
        libQt5Core.so.5
Annotations    :
        repo_type      : binary
        repository     : pcbsd-major
Flat size      : 17.8MiB
Description    :
PC-BSD Shell Utilities

WWW: https://github.com/pcbsd/pcbsd
    -------
So, what is the intent of '/usr/local/share/pcbsd/bin/pkg' script ?
Should '/usr/local/share/pcbsd/bin' be at the top of my default PATH
environment variable? One of the installs did this.
Is this a bug or 'operator error'?
If not a bug, any suggestions? 
In any case I would think an adjustment to the /usr/local/share/pcbsd/bin/pkg' script
would be in order. If the intent was not to handle any 'query' with spaces in the format, 
then there should be at least some basic input edit checking and print a proper error message(s).

**Comment by kmoore134** [comment]
Thanks for the bug report, this just reminded me to retire this script. (Its not used anymore)

https://github.com/pcbsd/pcbsd/commit/1e45ac673a423adc5e04ed7744446bcdd31b9a6c

You can remove it on your box, upcoming EDGE / PRODUCTION updates will remove it from PC-BSD automatically as well.
