### ISSUE TITLE
pkg fails to pootstrap. missing pkg.txz.sig

### ISSUE THREAD

**Issue by mrT55** [pcbsd/pcbsd#75]
uname -a
FreeBSD MT2007 10.1-RELEASE-p17 FreeBSD 10.1-RELEASE-p17 #0: Wed Feb 25 19:37:57 UTC 2015     root@amd64-builder.pcbsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

KDE: 4.14.2_5

# pkg info -f pkg
    The package management tool is not yet installed on your system.
    Do you want to fetch and install it now? [y/N]: y
    Bootstrapping pkg from http://pkg.cdn.pcbsd.org/10.0-RELEASE/edge/amd64, please wait...
    Signature for pkg not available.
    pkg: Error fetching http://pkg.cdn.pcbsd.org/10.0-RELEASE/edge/amd64/Latest/pkg.txz.sig: Not Found
    A pre-built version of pkg could not be found for your system.
    Consider changing PACKAGESITE or installing it from ports: 'ports-mgmt/pkg'.

With a browser: http://pkg.cdn.pcbsd.org/10.0-RELEASE/edge/amd64/Latest/
and 'pkg.txz.sig' is clearly not there.

**Comment by kmoore134** [comment]
Thanks, I talked to Bapt and found the fix. Next package sets will include the .sig file for pkg.txz automatically.
