### ISSUE TITLE
custom .conf settings lost after pc-updatemanager fbsdupdate

### ISSUE THREAD

**Issue by mrT55** [pcbsd/pcbsd#76]
uname -a
FreeBSD MT2007 10.1-RELEASE-p17 FreeBSD 10.1-RELEASE-p17 #0: Wed Feb 25 19:37:57 UTC 2015     root@amd64-builder.pcbsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

/usr/local/bin/pc-updatemanager was installed by package pcbsd-utils-1425579131

pkg info -f pcbsd-utils-1425579131
pcbsd-utils-1425579131
Name           : pcbsd-utils
Version        : 1425579131
Installed on   : Mon Mar  9 20:33:48 EDT 2015
Origin         : sysutils/pcbsd-utils
Architecture   : freebsd:10:x86:64
Prefix         : /usr/local
Categories     : sysutils
Licenses       : BSD
Maintainer     : kmoore@FreeBSD.org
WWW            : https://github.com/pcbsd/pcbsd
Comment        : PC-BSD Command-Line Utilities
Shared Libs required:
        libQt5Network.so.5
        libQt5Core.so.5
Annotations    :
        repo_type      : binary
        repository     : pcbsd-major
Flat size      : 17.8MiB
Description    :
PC-BSD Shell Utilities

WWW: https://github.com/pcbsd/pcbsd

--------

After running: pc-updatemanager fbsdupdate 
and reboot, I discovered that some .conf files had been updated.
Also the /var/log/pc-updatemanager.log  does not list these.

For example:
   /usr/local/etc/cups/cupsd.conf
   /usr/local/etc/cups/cups-pdf.conf 
Both had my custom settings reset to the default values.

It is my understanding that the designated user .conf files in: '/etc' and '/usr/local/etc'
when modified from their default settings should not be touched by any updates.
If this is not the case, what is pc-bsd.org's position on how a user can make .conf changes
to the files documened for user modification without loosing those changes as a result of an update?

**Comment by kmoore134** [comment]
Fixed!
https://github.com/pcbsd/pcbsd/commit/98cd4a50b8e56ece38c91a45a4e6f429891c9ddd

You are correct, that was a bug. Some of the .conf files were in the wrong location in our git repo, and it was incorrectly overwriting them with updates.
