### ISSUE TITLE
runScript isn't runned when is defined in pcinstall.cfg

### ISSUE THREAD

**Issue by angelescuo** [pcbsd/pcbsd#95]
Hi,
I am trying to help Eric Turgeon for GhostBSD project.
We use pc-sysinstall as backend for our's installer.
According http://wiki.pcbsd.org/index.php/Creating_an_Automated_Installation_with_pc-sysinstall/10.0/en if we define runScript=.... in pcinstall.cfg desired script should be copied under ${FSMNT} and launched there using run_chroot_script. in   ${FSMNT} chroot.
runScript isn't launched after user has been adeed in fact isn't launched at all.
Thank you

**Comment by angelescuo** [comment]
pcinstall.cfg is:
# Installation Mode
installMode=fresh
installInteractive=no
installType=GhostBSD
installMedium=dvd
packageType=livecd

# System Language
localizeLang=en
localizeKeyLayout=us

# Timezone
timeZone=Europe/Bucharest

# Disk Setup
disk0=ada0
partition=all
bootManager=grub
partscheme=GPT
commitDiskPart

# Partition Setup
disk0-part=UFS+SUJ 8795 /
disk0-part=SWAP 0 none
commitDiskLabel

# Network Configuration
hostname=tester.ghostbsd-pc.home

# Network Configuration

# Set the root pass
rootPass=tester

# Setup user
userName=tester
userComment=tester
userPass=tester
userShell=/bin/sh
userHome=/home/tester
defaultGroup=wheel
userGroups=operator
commitUser
runScript=/usr/local/bin/iso_to_hd

pc-sysinstall.log is:
kern.geom.debugflags: 0 -> 16
kern.geom.label.disk_ident.enable: 0 -> 0
Deleting all gparts
Running: gpart delete -i 1 /dev/ada0
ada0p1 deleted
Running: gpart delete -i 2 /dev/ada0
ada0p2 deleted
Running: gpart delete -i 3 /dev/ada0
ada0p3 deleted
Running: gpart destroy /dev/ada0
ada0 destroyed
Clearing gpt backup table location on disk
Running: dd if=/dev/zero of=/dev/ada0 bs=1m count=1
1+0 records in
1+0 records out
1048576 bytes transferred in 0.011900 secs (88116014 bytes/sec)
Running: dd if=/dev/zero of=/dev/ada0 bs=1m oseek=10814
dd: /dev/ada0: end of device
5+0 records in
4+0 records out
4194304 bytes transferred in 0.012398 secs (338304764 bytes/sec)
Running: dd if=/dev/zero of=/dev/ada0 count=3000
3000+0 records in
3000+0 records out
1536000 bytes transferred in 0.245976 secs (6244512 bytes/sec)
Running gpart on /dev/ada0
Running: gpart create -s GPT -f active /dev/ada0
ada0 created
Running: gpart add -s 1M -t bios-boot /dev/ada0
ada0p1 added
Running: gpart add -s 8795M -t freebsd-ufs /dev/ada0
ada0p2 added
Running: gpart add -s 2018M -t freebsd-swap /dev/ada0
ada0p3 added
Running: gpart bootcode -p /boot/gptboot -i 1 /dev/ada0
NEWFS: /dev/ada0p2 - UFS+SUJ
Running: newfs -t  -U /dev/ada0p2
/dev/ada0p2: 8795.0MB (18012160 sectors) block size 32768, fragment size 4096
	using 15 cylinder groups of 626.09MB, 20035 blks, 80256 inodes.
	with soft updates
super-block backups (for fsck_ffs -b #) at:
 192, 1282432, 2564672, 3846912, 5129152, 6411392, 7693632, 8975872, 10258112,
 11540352, 12822592, 14104832, 15387072, 16669312, 17951552
Running: sync
Running: tunefs -j enable /dev/ada0p2
tunefs: soft updates journaling set
Using inode 4 in cg 0 for 33554432 byte journal
Running: sync
Running: glabel label rootfs0 /dev/ada0p2
Running: sync
Running: sync
Running: glabel label swap0 /dev/ada0p3
Running: sync
mount -o rw /dev/ada0p2 -> /mnt/
Running: mount -o rw /dev/ada0p2 /mnt/
FOUND DVD: /dev/cd0
pc-sysinstall: Starting Extraction
pc-sysinstall: Extraction Finished
Running chroot command: /usr/bin/cap_mkdb /etc/login.conf
Running chroot command: pw userdel -n ghostbsd
Running chroot command: rm -rf /home/ghostbsd
Running chroot command: cat /.tmpPass | pw useradd -n tester -c "tester" -h 0 -s "/bin/sh" -m -d "/home/tester" -g "wheel" -G "operator"
Running: rm /mnt/.tmpPass
Setting hostname: tester.ghostbsd-pc.home
Setting root password
Running chroot command: cat /.rootpw | pw usermod root -h 0
Running: rm /mnt/.rootpw
Running: mount -t devfs devfs /mnt/dev
Running: ln -s ../zfs /mnt/boot/kernel/zfs
Running: cp /etc/hostid /mnt/etc/hostid
Running: chroot /mnt grub-install  --force /dev/ada0
Installing for i386-pc platform.
Installation finished. No error reported.
Running: chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
Generating grub configuration file ...
Found theme: /boot/grub/themes/ghostbsd/theme.txt
Found kernel of FreeBSD: /boot/kernel/kernel
Found kernel module directory: /boot/kernel
grub-probe: error: unknown filesystem.
done
Running: umount /mnt/dev
Running: swapoff /dev/ada0p3
swapoff: /dev/ada0p3: Invalid argument
Unmounting: /mnt
Running: umount -f /mnt
Unmounting DVD/USB media: /cdmnt-install
Running: umount -f /cdmnt-install
Installation finished!

If you will notice no log anbout runScript there.
Thank you.

**Comment by angelescuo** [comment]
iso_to hd is a simple echo "message" > /isotohd
of course with bin/sh shell

**Comment by kmoore134** [comment]
On 07/09/2015 16:14, angelescuo wrote:
>
> iso_to hd is a simple echo "message" > /isotohd
> of course with bin/sh shell
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pcbsd/pcbsd/issues/95#issuecomment-120133122>.
>

Your script looks fine. Just for kicks, can you also add the following
and test?

runCommand=<some bogus command>
runExtCommand=<some bogus command>

I want to see if those get run / logged also, it'll help me determine
which part of the code is failing.

Also, you don't have any whitespace before runScript= right? It's
checking for it to be the first thing on the line.


-- 
Kris Moore
PC-BSD Software / iXsystems
Enterprise Storage & Servers Driven By Open Source

**Comment by ericbsd** [comment]
I am not sure if it is problem, but it was missing new line in my python code I got told that might be the problem. I have start a new build, but I have not tested it yet. It might be solved.

**Comment by ericbsd** [comment]
Kris that issue can be close it is working now that I have put a new line in my code, f.writelines('runScript=/usr/local/bin/iso_to_hd\n') it was not pc-sysinstall problem.
